; 
; 
; Copyright (c) 2015-2017 by blindtiger ( blindtiger@foxmail.com )
; 
; The contents of this file are subject to the Mozilla Public License Version
; 2.0 (the "License"); you may not use this file except in compliance with
; the License. You may obtain a copy of the License at
; http://www.mozilla.org/MPL/
; 
; Software distributed under the License is distributed on an "AS IS" basis,
; WITHOUT WARRANTY OF ANY KIND, either express or implied. Ree the License
; for the specific language governing rights and limitations under the
; License.
; 
; The Initial Developer of the Original e is blindtiger.
; 
; 

OPTION CASEMAP:NONE

BuildStubs PROTO

_DATA$00 SEGMENT PAGE 'DATA'

_DATA$00 ENDS

_TEXT$00 SEGMENT PAGE 'CODE'

SYSSTUBS_ENTRY macro Name

    Stub&Name :
            mov rax, Stub&Name      ; save IP
            push rax
            mov rax, StubsBridge
            jmp rax
        DB  41 dup (0cch)           ; fill align 40h
    
    PUBLIC Stub&Name

ENDM

FirstStub :
PUBLIC FirstStub

SYSSTUBS_ENTRY AcceptConnectPort
SYSSTUBS_ENTRY AccessCheck
SYSSTUBS_ENTRY AccessCheckAndAuditAlarm
SYSSTUBS_ENTRY AccessCheckByType
SYSSTUBS_ENTRY AccessCheckByTypeAndAuditAlarm
SYSSTUBS_ENTRY AccessCheckByTypeResultList
SYSSTUBS_ENTRY AccessCheckByTypeResultListAndAuditAlarm
SYSSTUBS_ENTRY AccessCheckByTypeResultListAndAuditAlarmByHandle
SYSSTUBS_ENTRY AcquireCMFViewOwnership
SYSSTUBS_ENTRY AcquireProcessActivityReference
SYSSTUBS_ENTRY AddAtom
SYSSTUBS_ENTRY AddAtomEx
SYSSTUBS_ENTRY AddBootEntry
SYSSTUBS_ENTRY AddDriverEntry
SYSSTUBS_ENTRY AdjustGroupsToken
SYSSTUBS_ENTRY AdjustPrivilegesToken
SYSSTUBS_ENTRY AdjustTokenClaimsAndDeviceGroups
SYSSTUBS_ENTRY AlertResumeThread
SYSSTUBS_ENTRY AlertThread
SYSSTUBS_ENTRY AlertThreadByThreadId
SYSSTUBS_ENTRY AllocateLocallyUniqueId
SYSSTUBS_ENTRY AllocateReserveObject
SYSSTUBS_ENTRY AllocateUserPhysicalPages
SYSSTUBS_ENTRY AllocateUuids
SYSSTUBS_ENTRY AllocateVirtualMemory
SYSSTUBS_ENTRY AllocateVirtualMemoryEx
SYSSTUBS_ENTRY AlpcAcceptConnectPort
SYSSTUBS_ENTRY AlpcCancelMessage
SYSSTUBS_ENTRY AlpcConnectPort
SYSSTUBS_ENTRY AlpcConnectPortEx
SYSSTUBS_ENTRY AlpcCreatePort
SYSSTUBS_ENTRY AlpcCreatePortSection
SYSSTUBS_ENTRY AlpcCreateResourceReserve
SYSSTUBS_ENTRY AlpcCreateSectionView
SYSSTUBS_ENTRY AlpcCreateSecurityContext
SYSSTUBS_ENTRY AlpcDeletePortSection
SYSSTUBS_ENTRY AlpcDeleteResourceReserve
SYSSTUBS_ENTRY AlpcDeleteSectionView
SYSSTUBS_ENTRY AlpcDeleteSecurityContext
SYSSTUBS_ENTRY AlpcDisconnectPort
SYSSTUBS_ENTRY AlpcImpersonateClientContainerOfPort
SYSSTUBS_ENTRY AlpcImpersonateClientOfPort
SYSSTUBS_ENTRY AlpcOpenSenderProcess
SYSSTUBS_ENTRY AlpcOpenSenderThread
SYSSTUBS_ENTRY AlpcQueryInformation
SYSSTUBS_ENTRY AlpcQueryInformationMessage
SYSSTUBS_ENTRY AlpcRevokeSecurityContext
SYSSTUBS_ENTRY AlpcSendWaitReceivePort
SYSSTUBS_ENTRY AlpcSetInformation
SYSSTUBS_ENTRY ApphelpCacheContro
SYSSTUBS_ENTRY AreMappedFilesTheSame
SYSSTUBS_ENTRY AssignProcessToJobObject
SYSSTUBS_ENTRY AssociateWaitCompletionPacket
SYSSTUBS_ENTRY CallEnclave
SYSSTUBS_ENTRY CallbackReturn
SYSSTUBS_ENTRY CancelDeviceWakeupRequest
SYSSTUBS_ENTRY CancelIoFile
SYSSTUBS_ENTRY CancelIoFileEx
SYSSTUBS_ENTRY CancelSynchronousIoFile
SYSSTUBS_ENTRY CancelTimer
SYSSTUBS_ENTRY CancelTimer2
SYSSTUBS_ENTRY CancelWaitCompletionPacket
SYSSTUBS_ENTRY ClearAllSavepointsTransaction
SYSSTUBS_ENTRY ClearEvent
SYSSTUBS_ENTRY ClearSavepointTransaction
SYSSTUBS_ENTRY Close
SYSSTUBS_ENTRY CloseObjectAuditAlarm
SYSSTUBS_ENTRY CommitComplete
SYSSTUBS_ENTRY CommitEnlistment
SYSSTUBS_ENTRY CommitRegistryTransaction
SYSSTUBS_ENTRY CommitTransaction
SYSSTUBS_ENTRY CompactKeys
SYSSTUBS_ENTRY CompareObjects
SYSSTUBS_ENTRY CompareSigningLevels
SYSSTUBS_ENTRY CompareTokens
SYSSTUBS_ENTRY CompleteConnectPort
SYSSTUBS_ENTRY CompressKey
SYSSTUBS_ENTRY ConnectPort
SYSSTUBS_ENTRY Continue
SYSSTUBS_ENTRY ConvertBetweenAuxiliaryCounterAndPerformanceCounter
SYSSTUBS_ENTRY CreateDebugObject
SYSSTUBS_ENTRY CreateDirectoryObject
SYSSTUBS_ENTRY CreateDirectoryObjectEx
SYSSTUBS_ENTRY CreateEnclave
SYSSTUBS_ENTRY CreateEnlistment
SYSSTUBS_ENTRY CreateEvent
SYSSTUBS_ENTRY CreateEventPair
SYSSTUBS_ENTRY CreateFile
SYSSTUBS_ENTRY CreateIRTimer
SYSSTUBS_ENTRY CreateIoCompletion
SYSSTUBS_ENTRY CreateJobObject
SYSSTUBS_ENTRY CreateJobSet
SYSSTUBS_ENTRY CreateKey
SYSSTUBS_ENTRY CreateKeyTransacted
SYSSTUBS_ENTRY CreateKeyedEvent
SYSSTUBS_ENTRY CreateLowBoxToken
SYSSTUBS_ENTRY CreateMailslotFile
SYSSTUBS_ENTRY CreateMutant
SYSSTUBS_ENTRY CreateNamedPipeFile
SYSSTUBS_ENTRY CreatePagingFile
SYSSTUBS_ENTRY CreatePartition
SYSSTUBS_ENTRY CreatePort
SYSSTUBS_ENTRY CreatePrivateNamespace
SYSSTUBS_ENTRY CreateProcess
SYSSTUBS_ENTRY CreateProcessEx
SYSSTUBS_ENTRY CreateProfile
SYSSTUBS_ENTRY CreateProfileEx
SYSSTUBS_ENTRY CreateRegistryTransaction
SYSSTUBS_ENTRY CreateResourceManager
SYSSTUBS_ENTRY CreateSection
SYSSTUBS_ENTRY CreateSemaphore
SYSSTUBS_ENTRY CreateSymbolicLinkObject
SYSSTUBS_ENTRY CreateThread
SYSSTUBS_ENTRY CreateThreadEx
SYSSTUBS_ENTRY CreateTimer
SYSSTUBS_ENTRY CreateTimer2
SYSSTUBS_ENTRY CreateToken
SYSSTUBS_ENTRY CreateTokenEx
SYSSTUBS_ENTRY CreateTransaction
SYSSTUBS_ENTRY CreateTransactionManager
SYSSTUBS_ENTRY CreateUserProcess
SYSSTUBS_ENTRY CreateWaitCompletionPacket
SYSSTUBS_ENTRY CreateWaitablePort
SYSSTUBS_ENTRY CreateWnfStateName
SYSSTUBS_ENTRY CreateWorkerFactory
SYSSTUBS_ENTRY DebugActiveProcess
SYSSTUBS_ENTRY DebugContinue
SYSSTUBS_ENTRY DelayExecution
SYSSTUBS_ENTRY DeleteAtom
SYSSTUBS_ENTRY DeleteBootEntry
SYSSTUBS_ENTRY DeleteDriverEntry
SYSSTUBS_ENTRY DeleteFile
SYSSTUBS_ENTRY DeleteKey
SYSSTUBS_ENTRY DeleteObjectAuditAlarm
SYSSTUBS_ENTRY DeletePrivateNamespace
SYSSTUBS_ENTRY DeleteValueKey
SYSSTUBS_ENTRY DeleteWnfStateData
SYSSTUBS_ENTRY DeleteWnfStateName
SYSSTUBS_ENTRY DeviceIoControlFile
SYSSTUBS_ENTRY DisableLastKnownGood
SYSSTUBS_ENTRY DisplayString
SYSSTUBS_ENTRY DrawText
SYSSTUBS_ENTRY DuplicateObject
SYSSTUBS_ENTRY DuplicateToken
SYSSTUBS_ENTRY EnableLastKnownGood
SYSSTUBS_ENTRY EnumerateBootEntries
SYSSTUBS_ENTRY EnumerateDriverEntries
SYSSTUBS_ENTRY EnumerateKey
SYSSTUBS_ENTRY EnumerateSystemEnvironmentValuesEx
SYSSTUBS_ENTRY EnumerateTransactionObject
SYSSTUBS_ENTRY EnumerateValueKey
SYSSTUBS_ENTRY ExtendSection
SYSSTUBS_ENTRY FilterBootOption
SYSSTUBS_ENTRY FilterToken
SYSSTUBS_ENTRY FilterTokenEx
SYSSTUBS_ENTRY FindAtom
SYSSTUBS_ENTRY FlushBuffersFile
SYSSTUBS_ENTRY FlushBuffersFileEx
SYSSTUBS_ENTRY FlushInstallUILanguage
SYSSTUBS_ENTRY FlushInstructionCache
SYSSTUBS_ENTRY FlushKey
SYSSTUBS_ENTRY FlushProcessWriteBuffers
SYSSTUBS_ENTRY FlushVirtualMemory
SYSSTUBS_ENTRY FlushWriteBuffer
SYSSTUBS_ENTRY FreeUserPhysicalPages
SYSSTUBS_ENTRY FreeVirtualMemory
SYSSTUBS_ENTRY FreezeRegistry
SYSSTUBS_ENTRY FreezeTransactions
SYSSTUBS_ENTRY FsControlFile
SYSSTUBS_ENTRY GetCachedSigningLeve
SYSSTUBS_ENTRY GetCompleteWnfStateSubscription
SYSSTUBS_ENTRY GetContextThread
SYSSTUBS_ENTRY GetCurrentProcessorNumber
SYSSTUBS_ENTRY GetCurrentProcessorNumberEx
SYSSTUBS_ENTRY GetDevicePowerState
SYSSTUBS_ENTRY GetMUIRegistryInfo
SYSSTUBS_ENTRY GetNextProcess
SYSSTUBS_ENTRY GetNextThread
SYSSTUBS_ENTRY GetNlsSectionPtr
SYSSTUBS_ENTRY GetNotificationResourceManager
SYSSTUBS_ENTRY GetPlugPlayEvent
SYSSTUBS_ENTRY GetWriteWatch
SYSSTUBS_ENTRY ImpersonateAnonymousToken
SYSSTUBS_ENTRY ImpersonateClientOfPort
SYSSTUBS_ENTRY ImpersonateThread
SYSSTUBS_ENTRY InitializeEnclave
SYSSTUBS_ENTRY InitializeNlsFiles
SYSSTUBS_ENTRY InitializeRegistry
SYSSTUBS_ENTRY InitiatePowerAction
SYSSTUBS_ENTRY IsProcessInJob
SYSSTUBS_ENTRY IsSystemResumeAutomatic
SYSSTUBS_ENTRY IsUILanguageComitted
SYSSTUBS_ENTRY ListTransactions
SYSSTUBS_ENTRY ListenPort
SYSSTUBS_ENTRY LoadDriver
SYSSTUBS_ENTRY LoadEnclaveData
SYSSTUBS_ENTRY LoadHotPatch
SYSSTUBS_ENTRY LoadKey
SYSSTUBS_ENTRY LoadKey2
SYSSTUBS_ENTRY LoadKeyEx
SYSSTUBS_ENTRY LockFile
SYSSTUBS_ENTRY LockProductActivationKeys
SYSSTUBS_ENTRY LockRegistryKey
SYSSTUBS_ENTRY LockVirtualMemory
SYSSTUBS_ENTRY MakePermanentObject
SYSSTUBS_ENTRY MakeTemporaryObject
SYSSTUBS_ENTRY ManagePartition
SYSSTUBS_ENTRY MapCMFModule
SYSSTUBS_ENTRY MapUserPhysicalPages
SYSSTUBS_ENTRY MapUserPhysicalPagesScatter
SYSSTUBS_ENTRY MapViewOfSection
SYSSTUBS_ENTRY MapViewOfSectionEx
SYSSTUBS_ENTRY MarshallTransaction
SYSSTUBS_ENTRY ModifyBootEntry
SYSSTUBS_ENTRY ModifyDriverEntry
SYSSTUBS_ENTRY NotifyChangeDirectoryFile
SYSSTUBS_ENTRY NotifyChangeDirectoryFileEx
SYSSTUBS_ENTRY NotifyChangeKey
SYSSTUBS_ENTRY NotifyChangeMultipleKeys
SYSSTUBS_ENTRY NotifyChangeSession
SYSSTUBS_ENTRY OpenDirectoryObject
SYSSTUBS_ENTRY OpenEnlistment
SYSSTUBS_ENTRY OpenEvent
SYSSTUBS_ENTRY OpenEventPair
SYSSTUBS_ENTRY OpenFile
SYSSTUBS_ENTRY OpenIoCompletion
SYSSTUBS_ENTRY OpenJobObject
SYSSTUBS_ENTRY OpenKey
SYSSTUBS_ENTRY OpenKeyEx
SYSSTUBS_ENTRY OpenKeyTransacted
SYSSTUBS_ENTRY OpenKeyTransactedEx
SYSSTUBS_ENTRY OpenKeyedEvent
SYSSTUBS_ENTRY OpenMutant
SYSSTUBS_ENTRY OpenObjectAuditAlarm
SYSSTUBS_ENTRY OpenPartition
SYSSTUBS_ENTRY OpenPrivateNamespace
SYSSTUBS_ENTRY OpenProcess
SYSSTUBS_ENTRY OpenProcessToken
SYSSTUBS_ENTRY OpenProcessTokenEx
SYSSTUBS_ENTRY OpenRegistryTransaction
SYSSTUBS_ENTRY OpenResourceManager
SYSSTUBS_ENTRY OpenSection
SYSSTUBS_ENTRY OpenSemaphore
SYSSTUBS_ENTRY OpenSession
SYSSTUBS_ENTRY OpenSymbolicLinkObject
SYSSTUBS_ENTRY OpenThread
SYSSTUBS_ENTRY OpenThreadToken
SYSSTUBS_ENTRY OpenThreadTokenEx
SYSSTUBS_ENTRY OpenTimer
SYSSTUBS_ENTRY OpenTransaction
SYSSTUBS_ENTRY OpenTransactionManager
SYSSTUBS_ENTRY PlugPlayContro
SYSSTUBS_ENTRY PowerInformation
SYSSTUBS_ENTRY PrePrepareComplete
SYSSTUBS_ENTRY PrePrepareEnlistment
SYSSTUBS_ENTRY PrepareComplete
SYSSTUBS_ENTRY PrepareEnlistment
SYSSTUBS_ENTRY PrivilegeCheck
SYSSTUBS_ENTRY PrivilegeObjectAuditAlarm
SYSSTUBS_ENTRY PrivilegedServiceAuditAlarm
SYSSTUBS_ENTRY PropagationComplete
SYSSTUBS_ENTRY PropagationFailed
SYSSTUBS_ENTRY ProtectVirtualMemory
SYSSTUBS_ENTRY PullTransaction
SYSSTUBS_ENTRY PulseEvent
SYSSTUBS_ENTRY QueryAttributesFile
SYSSTUBS_ENTRY QueryAuxiliaryCounterFrequency
SYSSTUBS_ENTRY QueryBootEntryOrder
SYSSTUBS_ENTRY QueryBootOptions
SYSSTUBS_ENTRY QueryDebugFilterState
SYSSTUBS_ENTRY QueryDefaultLocale
SYSSTUBS_ENTRY QueryDefaultUILanguage
SYSSTUBS_ENTRY QueryDirectoryFile
SYSSTUBS_ENTRY QueryDirectoryFileEx
SYSSTUBS_ENTRY QueryDirectoryObject
SYSSTUBS_ENTRY QueryDriverEntryOrder
SYSSTUBS_ENTRY QueryEaFile
SYSSTUBS_ENTRY QueryEvent
SYSSTUBS_ENTRY QueryFullAttributesFile
SYSSTUBS_ENTRY QueryInformationAtom
SYSSTUBS_ENTRY QueryInformationByName
SYSSTUBS_ENTRY QueryInformationEnlistment
SYSSTUBS_ENTRY QueryInformationFile
SYSSTUBS_ENTRY QueryInformationJobObject
SYSSTUBS_ENTRY QueryInformationPort
SYSSTUBS_ENTRY QueryInformationProcess
SYSSTUBS_ENTRY QueryInformationResourceManager
SYSSTUBS_ENTRY QueryInformationThread
SYSSTUBS_ENTRY QueryInformationToken
SYSSTUBS_ENTRY QueryInformationTransaction
SYSSTUBS_ENTRY QueryInformationTransactionManager
SYSSTUBS_ENTRY QueryInformationWorkerFactory
SYSSTUBS_ENTRY QueryInstallUILanguage
SYSSTUBS_ENTRY QueryIntervalProfile
SYSSTUBS_ENTRY QueryIoCompletion
SYSSTUBS_ENTRY QueryKey
SYSSTUBS_ENTRY QueryLicenseValue
SYSSTUBS_ENTRY QueryMultipleValueKey
SYSSTUBS_ENTRY QueryMutant
SYSSTUBS_ENTRY QueryObject
SYSSTUBS_ENTRY QueryOpenSubKeys
SYSSTUBS_ENTRY QueryOpenSubKeysEx
SYSSTUBS_ENTRY QueryPerformanceCounter
SYSSTUBS_ENTRY QueryPortInformationProcess
SYSSTUBS_ENTRY QueryQuotaInformationFile
SYSSTUBS_ENTRY QuerySection
SYSSTUBS_ENTRY QuerySecurityAttributesToken
SYSSTUBS_ENTRY QuerySecurityObject
SYSSTUBS_ENTRY QuerySecurityPolicy
SYSSTUBS_ENTRY QuerySemaphore
SYSSTUBS_ENTRY QuerySymbolicLinkObject
SYSSTUBS_ENTRY QuerySystemEnvironmentValue
SYSSTUBS_ENTRY QuerySystemEnvironmentValueEx
SYSSTUBS_ENTRY QuerySystemInformation
SYSSTUBS_ENTRY QuerySystemInformationEx
SYSSTUBS_ENTRY QuerySystemTime
SYSSTUBS_ENTRY QueryTimer
SYSSTUBS_ENTRY QueryTimerResolution
SYSSTUBS_ENTRY QueryValueKey
SYSSTUBS_ENTRY QueryVirtualMemory
SYSSTUBS_ENTRY QueryVolumeInformationFile
SYSSTUBS_ENTRY QueryWnfStateData
SYSSTUBS_ENTRY QueryWnfStateNameInformation
SYSSTUBS_ENTRY QueueApcThread
SYSSTUBS_ENTRY QueueApcThreadEx
SYSSTUBS_ENTRY RaiseException
SYSSTUBS_ENTRY RaiseHardError
SYSSTUBS_ENTRY ReadFile
SYSSTUBS_ENTRY ReadFileScatter
SYSSTUBS_ENTRY ReadOnlyEnlistment
SYSSTUBS_ENTRY ReadRequestData
SYSSTUBS_ENTRY ReadVirtualMemory
SYSSTUBS_ENTRY RecoverEnlistment
SYSSTUBS_ENTRY RecoverResourceManager
SYSSTUBS_ENTRY RecoverTransactionManager
SYSSTUBS_ENTRY RegisterProtocolAddressInformation
SYSSTUBS_ENTRY RegisterThreadTerminatePort
SYSSTUBS_ENTRY ReleaseCMFViewOwnership
SYSSTUBS_ENTRY ReleaseKeyedEvent
SYSSTUBS_ENTRY ReleaseMutant
SYSSTUBS_ENTRY ReleaseSemaphore
SYSSTUBS_ENTRY ReleaseWorkerFactoryWorker
SYSSTUBS_ENTRY RemoveIoCompletion
SYSSTUBS_ENTRY RemoveIoCompletionEx
SYSSTUBS_ENTRY RemoveProcessDebug
SYSSTUBS_ENTRY RenameKey
SYSSTUBS_ENTRY RenameTransactionManager
SYSSTUBS_ENTRY ReplaceKey
SYSSTUBS_ENTRY ReplacePartitionUnit
SYSSTUBS_ENTRY ReplyPort
SYSSTUBS_ENTRY ReplyWaitReceivePort
SYSSTUBS_ENTRY ReplyWaitReceivePortEx
SYSSTUBS_ENTRY ReplyWaitReplyPort
SYSSTUBS_ENTRY RequestDeviceWakeup
SYSSTUBS_ENTRY RequestPort
SYSSTUBS_ENTRY RequestWaitReplyPort
SYSSTUBS_ENTRY RequestWakeupLatency
SYSSTUBS_ENTRY ResetEvent
SYSSTUBS_ENTRY ResetWriteWatch
SYSSTUBS_ENTRY RestoreKey
SYSSTUBS_ENTRY ResumeProcess
SYSSTUBS_ENTRY ResumeThread
SYSSTUBS_ENTRY RevertContainerImpersonation
SYSSTUBS_ENTRY RollbackComplete
SYSSTUBS_ENTRY RollbackEnlistment
SYSSTUBS_ENTRY RollbackRegistryTransaction
SYSSTUBS_ENTRY RollbackSavepointTransaction
SYSSTUBS_ENTRY RollbackTransaction
SYSSTUBS_ENTRY RollforwardTransactionManager
SYSSTUBS_ENTRY SaveKey
SYSSTUBS_ENTRY SaveKeyEx
SYSSTUBS_ENTRY SaveMergedKeys
SYSSTUBS_ENTRY SavepointComplete
SYSSTUBS_ENTRY SavepointTransaction
SYSSTUBS_ENTRY SecureConnectPort
SYSSTUBS_ENTRY SerializeBoot
SYSSTUBS_ENTRY SetBootEntryOrder
SYSSTUBS_ENTRY SetBootOptions
SYSSTUBS_ENTRY SetCachedSigningLeve
SYSSTUBS_ENTRY SetCachedSigningLevel2
SYSSTUBS_ENTRY SetContextThread
SYSSTUBS_ENTRY SetDebugFilterState
SYSSTUBS_ENTRY SetDefaultHardErrorPort
SYSSTUBS_ENTRY SetDefaultLocale
SYSSTUBS_ENTRY SetDefaultUILanguage
SYSSTUBS_ENTRY SetDriverEntryOrder
SYSSTUBS_ENTRY SetEaFile
SYSSTUBS_ENTRY SetEvent
SYSSTUBS_ENTRY SetEventBoostPriority
SYSSTUBS_ENTRY SetHighEventPair
SYSSTUBS_ENTRY SetHighWaitLowEventPair
SYSSTUBS_ENTRY SetIRTimer
SYSSTUBS_ENTRY SetInformationDebugObject
SYSSTUBS_ENTRY SetInformationEnlistment
SYSSTUBS_ENTRY SetInformationFile
SYSSTUBS_ENTRY SetInformationJobObject
SYSSTUBS_ENTRY SetInformationKey
SYSSTUBS_ENTRY SetInformationObject
SYSSTUBS_ENTRY SetInformationProcess
SYSSTUBS_ENTRY SetInformationResourceManager
SYSSTUBS_ENTRY SetInformationSymbolicLink
SYSSTUBS_ENTRY SetInformationThread
SYSSTUBS_ENTRY SetInformationToken
SYSSTUBS_ENTRY SetInformationTransaction
SYSSTUBS_ENTRY SetInformationTransactionManager
SYSSTUBS_ENTRY SetInformationVirtualMemory
SYSSTUBS_ENTRY SetInformationWorkerFactory
SYSSTUBS_ENTRY SetIntervalProfile
SYSSTUBS_ENTRY SetIoCompletion
SYSSTUBS_ENTRY SetIoCompletionEx
SYSSTUBS_ENTRY SetLdtEntries
SYSSTUBS_ENTRY SetLowEventPair
SYSSTUBS_ENTRY SetLowWaitHighEventPair
SYSSTUBS_ENTRY SetQuotaInformationFile
SYSSTUBS_ENTRY SetSecurityObject
SYSSTUBS_ENTRY SetSystemEnvironmentValue
SYSSTUBS_ENTRY SetSystemEnvironmentValueEx
SYSSTUBS_ENTRY SetSystemInformation
SYSSTUBS_ENTRY SetSystemPowerState
SYSSTUBS_ENTRY SetSystemTime
SYSSTUBS_ENTRY SetThreadExecutionState
SYSSTUBS_ENTRY SetTimer
SYSSTUBS_ENTRY SetTimer2
SYSSTUBS_ENTRY SetTimerEx
SYSSTUBS_ENTRY SetTimerResolution
SYSSTUBS_ENTRY SetUuidSeed
SYSSTUBS_ENTRY SetValueKey
SYSSTUBS_ENTRY SetVolumeInformationFile
SYSSTUBS_ENTRY SetWnfProcessNotificationEvent
SYSSTUBS_ENTRY ShutdownSystem
SYSSTUBS_ENTRY ShutdownWorkerFactory
SYSSTUBS_ENTRY SignalAndWaitForSingleObject
SYSSTUBS_ENTRY SinglePhaseReject
SYSSTUBS_ENTRY StartProfile
SYSSTUBS_ENTRY StartTm
SYSSTUBS_ENTRY StopProfile
SYSSTUBS_ENTRY SubscribeWnfStateChange
SYSSTUBS_ENTRY SuspendProcess
SYSSTUBS_ENTRY SuspendThread
SYSSTUBS_ENTRY SystemDebugContro
SYSSTUBS_ENTRY TerminateEnclave
SYSSTUBS_ENTRY TerminateJobObject
SYSSTUBS_ENTRY TerminateProcess
SYSSTUBS_ENTRY TerminateThread
SYSSTUBS_ENTRY TestAlert
SYSSTUBS_ENTRY ThawRegistry
SYSSTUBS_ENTRY ThawTransactions
SYSSTUBS_ENTRY TraceContro
SYSSTUBS_ENTRY TraceEvent
SYSSTUBS_ENTRY TranslateFilePath
SYSSTUBS_ENTRY UmsThreadYield
SYSSTUBS_ENTRY UnloadDriver
SYSSTUBS_ENTRY UnloadKey
SYSSTUBS_ENTRY UnloadKey2
SYSSTUBS_ENTRY UnloadKeyEx
SYSSTUBS_ENTRY UnlockFile
SYSSTUBS_ENTRY UnlockVirtualMemory
SYSSTUBS_ENTRY UnmapViewOfSection
SYSSTUBS_ENTRY UnmapViewOfSectionEx
SYSSTUBS_ENTRY UnsubscribeWnfStateChange
SYSSTUBS_ENTRY UpdateWnfStateData
SYSSTUBS_ENTRY VdmContro
SYSSTUBS_ENTRY WaitForAlertByThreadId
SYSSTUBS_ENTRY WaitForDebugEvent
SYSSTUBS_ENTRY WaitForKeyedEvent
SYSSTUBS_ENTRY WaitForMultipleObjects
SYSSTUBS_ENTRY WaitForMultipleObjects32
SYSSTUBS_ENTRY WaitForSingleObject
SYSSTUBS_ENTRY WaitForWnfNotifications
SYSSTUBS_ENTRY WaitForWorkViaWorkerFactory
SYSSTUBS_ENTRY WaitHighEventPair
SYSSTUBS_ENTRY WaitLowEventPair
SYSSTUBS_ENTRY WorkerFactoryWorkerReady
SYSSTUBS_ENTRY WriteFile
SYSSTUBS_ENTRY WriteFileGather
SYSSTUBS_ENTRY WriteRequestData
SYSSTUBS_ENTRY WriteVirtualMemory
SYSSTUBS_ENTRY YieldExecution

StubsBridge :

                            ; [rsp + 8] caller
    mov [rsp + 10h], rcx    ; save argument register
    mov [rsp + 18h], rdx    ;
    mov [rsp + 20h], r8     ;
    mov [rsp + 28h], r9     ;
    sub rsp, 28h
    pushfq
    call BuildStubs         ; Build stubs
    popfq
    add rsp, 28h
    mov rcx, [rsp + 10h]    ; restore argument register
    mov rdx, [rsp + 18h]
    mov r8, [rsp + 20h]
    mov r9, [rsp + 28h]
    ret                     ; jmp caller (now the stubs table is ajust to system function)
DB  7 dup (0cch)

PUBLIC StubsBridge

_TEXT$00 ENDS

END
